[loggers]
keys=root,django,django.request,django.server,django.db.backends,app,errors

[handlers]
keys=app_file,error_file,console

[formatters]
keys=verbose,simple

[logger_root]
level=DEBUG
handlers=console
propagate=0

[logger_django]
level=INFO
handlers=app_file,error_file,console
qualname=django
propagate=0

[logger_django.request]
level=INFO
handlers=app_file,error_file,console
qualname=django.request
propagate=0

[logger_django.server]
level=INFO
handlers=app_file,console
qualname=django.server
propagate=0

[logger_django.db.backends]
level=DEBUG
handlers=app_file,console
qualname=django.db.backends
propagate=0

[logger_app]
level=DEBUG
handlers=app_file,console
qualname=app
propagate=0

[logger_errors]
level=ERROR
handlers=error_file,console
qualname=errors
propagate=0

[handler_app_file]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=verbose
args=('logs/app.log', 'midnight', 1, 30, 'utf-8')

[handler_error_file]
class=handlers.TimedRotatingFileHandler
level=ERROR
formatter=verbose
args=('logs/errors.log', 'midnight', 1, 90, 'utf-8')

[handler_console]
class=StreamHandler
level=DEBUG
formatter=simple
args=(sys.stdout,)

[formatter_verbose]
format=[%(asctime)s] [%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_simple]
format=[%(levelname)s] %(message)s
