# Generated by Django 5.0.14 on 2026-03-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(blank=True, max_length=100, verbose_name='Имя участника')),
                ('total_score', models.IntegerField(default=0, verbose_name='Всего баллов')),
                ('correct_answers_count', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в сессии',
                'verbose_name_plural': 'Участия в сессиях',
            },
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Получено баллов')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.answervariant', verbose_name='Выбранный ответ')),
                ('participant_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_sessions.participantsession', verbose_name='Участник сессии')),
            ],
            options={
                'verbose_name': 'Ответ участника',
                'verbose_name_plural': 'Ответы участников',
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=10, unique=True, verbose_name='Уникальный код для входа')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Пароль сессии')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активна'), ('finished', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizzes.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Сессия квиза',
                'verbose_name_plural': 'Сессии квизов',
            },
        ),
        migrations.AddField(
            model_name='participantsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz_sessions.quizsession', verbose_name='Сессия'),
        ),
        migrations.AlterUniqueTogether(
            name='participantsession',
            unique_together={('session', 'user')},
        ),
    ]
