# Generated by Django 5.0.14 on 2026-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantsession',
            options={'ordering': ['-total_score', 'time_spent_seconds'], 'verbose_name': 'Участие в сессии', 'verbose_name_plural': 'Участия в сессиях'},
        ),
        migrations.AddField(
            model_name='participantsession',
            name='incorrect_answers_count',
            field=models.IntegerField(default=0, verbose_name='Неправильных ответов'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='place_in_rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в рейтинге'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='score_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент правильных'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='skipped_answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено вопросов'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время прохождения (сек)'),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов'),
        ),
    ]
