# Generated by Django 5.0.14 on 2026-04-26 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Таймер (секунды)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Описание'),
        ),
    ]
