# Generated by Django 5.0.14 on 2026-05-24 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_text_alter_question_timer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='Название должно содержать минимум 3 символа')], verbose_name='Название'),
        ),
    ]
