# Generated by Django 5.0.14 on 2026-05-24 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_alter_question_text_alter_question_timer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answervariant",
            name="match_left_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID левой части соответствия"
            ),
        ),
        migrations.AddField(
            model_name="answervariant",
            name="match_right_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID правой части соответствия"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "Один правильный ответ"),
                    ("multiple", "Несколько правильных ответов"),
                    ("text", "Текстовый ответ"),
                    ("matching", "Сопоставление"),
                ],
                default="single",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, message="Название должно содержать минимум 3 символа"
                    )
                ],
                verbose_name="Название",
            ),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_variants", models.JSONField(default=list)),
                ("score", models.FloatField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="quizzes.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
    ]
