# Generated by Django 4.2.27 on 2026-05-11 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0002_alter_question_text_alter_question_timer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz', verbose_name='Квиз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия тренировки',
                'verbose_name_plural': 'Сессии тренировок',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Вопрос')),
                ('selected_variants', models.ManyToManyField(blank=True, to='quizzes.answervariant', verbose_name='Выбранные ответы')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='quizzes.trainingsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Прогресс тренировки',
                'verbose_name_plural': 'Прогресс тренировок',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
