# Generated by Django 5.0.14 on 2026-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="answervariant",
            name="match_left_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID левой части соответствия"
            ),
        ),
        migrations.AddField(
            model_name="answervariant",
            name="match_right_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID правой части соответствия"
            ),
        ),
    ]
