# Generated by Django 5.0.14 on 2026-05-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_answervariant_match_left_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="quiz_backgrounds/",
                verbose_name="Фоновое изображение",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="quiz_logos/", verbose_name="Логотип"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="В HEX формате, например #FF5733",
                max_length=7,
                null=True,
                verbose_name="Основной цвет",
            ),
        ),
    ]
