# Generated by Django 5.0.14 on 2026-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_quiz_background_image_quiz_logo_quiz_primary_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="answervariant",
            name="match_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Текст сопоставления",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "Один правильный ответ"),
                    ("multiple", "Несколько правильных ответов"),
                    ("text", "Текстовый ответ"),
                    ("matching", "Сопоставление"),
                ],
                default="single",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
