# Generated by Django 6.0 on 2026-03-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers_count', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='Всего попыток')),
                ('total_time_spent', models.FloatField(default=0.0, verbose_name='Общее время (сек)')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (1-5)')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='quizzes.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Статистика вопроса',
                'verbose_name_plural': 'Статистика вопросов',
            },
        ),
    ]
